<?php

/**
 * @file
 * Primary module hooks for Madrassa Niveaux module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function madrassa_niveaux_theme(): array {
  return [
    'madrassa_level' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for madrassa niveaux templates.
 *
 * Default template: madrassa-level.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the madrassa niveaux information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_madrassa_level(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function madrassa_niveaux_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish madrassa niveaucies.
      $storage = \Drupal::entityTypeManager()->getStorage('madrassa_level');
      $madrassa_level_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($madrassa_level_ids) as $madrassa_level) {
        $madrassa_level->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize madrassa niveaucies.
      $storage = \Drupal::entityTypeManager()->getStorage('madrassa_level');
      $madrassa_level_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($madrassa_level_ids) as $madrassa_level) {
        $madrassa_level->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function madrassa_niveaux_user_predelete(UserInterface $account): void {
  // Delete madrassa niveaucies that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('madrassa_level');
  $madrassa_level_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($madrassa_level_ids)
  );
}
