<?php


/**
 * hook_form_alter()
 */
function madrassa_content_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if (in_array($form_id, ['node_child_form', 'node_child_edit_form'])) {
    //$form['field_old']['widget'][0]['value']['#default_value'] = 'test';
  } 
}

/**
 * hook_page_attachments()
 */
function madrassa_content_page_attachments(array &$attachments) {
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  if ($theme == 'gin') {
    $attachments['#attached']['library'][] = 'madrassa_content/extra.admin';
  }
}

/**
 * Implements hook_user_login().
 */
function madrassa_content_user_login($account) {
  // dd($account);
  
}