<?php

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * hook_views_query_alte
 */
// function madrassa_content_views_query_alter(ViewExecutable $view, QueryPluginBase $query) 
// {
    // if ($view->id() == 'children' && $view->current_display == 'page_list_children') {
// 
        // $definition = [
            // 'table' => 'node__field_parent_id',
            // 'field' => 'field_parent_id_target_id',
            // 'left_table' => 'users_field_data',
            // 'left_field' => 'uid',
        // ];
        // $join = \Drupal::service('plugin.manager.views.join')->createInstance('standard', $definition);
        // $query->addRelationship('node__field_parent_id', $join, 'users_field_data');
        //$query->addWhereExpression('AND', 'users_field_data.uid = :uid', [':uid' => \Drupal::currentUser()->id()]);
    // }
// }