<?php


/**
 * hook_form_alter()
 */

use Drupal\Core\Url;

// function madrassa_content_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//   if (in_array($form_id, ['node_dashboard_form', 'node_dashboard_edit_form'])) {
//   //  dd($form['field_items']);
//   } 
// }


/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */

/**
 * hook_page_attachments()
 */
function madrassa_content_page_attachments(array &$attachments) {
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  if ($theme == 'gin') {
    $attachments['#attached']['library'][] = 'madrassa_content/extra.admin';
  }
}

/**
 * Implements hook_user_login().
 */
function madrassa_content_user_login($account) {
  $logged_in = \Drupal::currentUser()->isAuthenticated();
  // dd($logged_in);
  if ($logged_in) {
    $roles = $account->getRoles();
    if (in_array('administrator', $roles)) {
      // $response = new \Symfony\Component\HttpFoundation\RedirectResponse('/admin/dashboard');
      // $response->send();
    }
  }
  // foreach ($account->get('roles') as $role) {
  //   if ($role->entity->id() == 'administrator') {
  //     // $url = Url::fromRoute('madrassa_content.dashboard');
  //     $response = new \Symfony\Component\HttpFoundation\RedirectResponse('/admin/dashboard');
  //     $response->send();
  //   }
  // }
}

/**
 * hook_views_data_alter()
 */
function madrassa_content_views_data_alter(array &$data) {
 //dd($data);
}